#!/bin/sh

exec /app/jre/bin/java \
  --module-path /app/lib/javafx \
  --add-modules=javafx.controls,javafx.swing,javafx.media,javafx.web \
  -Djava.awt.headless=false \
  -Dawt.useSystemAAFontSettings=on \
  -Dswing.aatext=true \
  -jar /app/share/io.github.danmanima5_cmyk.MSC_Launcher/minecraft-launcher-2.2.0.jar \
  "$@"
